name: Wiki Deployment
on:
  push:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/publish-wiki.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@rsync
        with:
          path: "docs/"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.DEPLOY_TO_WIKI_ACCESS_TOKEN }}
